/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { OperatorService } from "../operator.service";
import { OperatorCreateInput } from "./OperatorCreateInput";
import { Operator } from "./Operator";
import { OperatorFindManyArgs } from "./OperatorFindManyArgs";
import { OperatorWhereUniqueInput } from "./OperatorWhereUniqueInput";
import { OperatorUpdateInput } from "./OperatorUpdateInput";

export class OperatorControllerBase {
  constructor(protected readonly service: OperatorService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Operator })
  async createOperator(
    @common.Body() data: OperatorCreateInput
  ): Promise<Operator> {
    return await this.service.createOperator({
      data: data,
      select: {
        bigoId: true,
        createdAt: true,
        diamondsAmount: true,
        id: true,
        operatorRole: true,
        organizationId: true,
        updatedAt: true,
        userName: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Operator] })
  @ApiNestedQuery(OperatorFindManyArgs)
  async operators(@common.Req() request: Request): Promise<Operator[]> {
    const args = plainToClass(OperatorFindManyArgs, request.query);
    return this.service.operators({
      ...args,
      select: {
        bigoId: true,
        createdAt: true,
        diamondsAmount: true,
        id: true,
        operatorRole: true,
        organizationId: true,
        updatedAt: true,
        userName: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Operator })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async operator(
    @common.Param() params: OperatorWhereUniqueInput
  ): Promise<Operator | null> {
    const result = await this.service.operator({
      where: params,
      select: {
        bigoId: true,
        createdAt: true,
        diamondsAmount: true,
        id: true,
        operatorRole: true,
        organizationId: true,
        updatedAt: true,
        userName: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Operator })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOperator(
    @common.Param() params: OperatorWhereUniqueInput,
    @common.Body() data: OperatorUpdateInput
  ): Promise<Operator | null> {
    try {
      return await this.service.updateOperator({
        where: params,
        data: data,
        select: {
          bigoId: true,
          createdAt: true,
          diamondsAmount: true,
          id: true,
          operatorRole: true,
          organizationId: true,
          updatedAt: true,
          userName: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Operator })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOperator(
    @common.Param() params: OperatorWhereUniqueInput
  ): Promise<Operator | null> {
    try {
      return await this.service.deleteOperator({
        where: params,
        select: {
          bigoId: true,
          createdAt: true,
          diamondsAmount: true,
          id: true,
          operatorRole: true,
          organizationId: true,
          updatedAt: true,
          userName: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
