/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Operator } from "./Operator";
import { OperatorCountArgs } from "./OperatorCountArgs";
import { OperatorFindManyArgs } from "./OperatorFindManyArgs";
import { OperatorFindUniqueArgs } from "./OperatorFindUniqueArgs";
import { CreateOperatorArgs } from "./CreateOperatorArgs";
import { UpdateOperatorArgs } from "./UpdateOperatorArgs";
import { DeleteOperatorArgs } from "./DeleteOperatorArgs";
import { OperatorService } from "../operator.service";
@graphql.Resolver(() => Operator)
export class OperatorResolverBase {
  constructor(protected readonly service: OperatorService) {}

  async _operatorsMeta(
    @graphql.Args() args: OperatorCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Operator])
  async operators(
    @graphql.Args() args: OperatorFindManyArgs
  ): Promise<Operator[]> {
    return this.service.operators(args);
  }

  @graphql.Query(() => Operator, { nullable: true })
  async operator(
    @graphql.Args() args: OperatorFindUniqueArgs
  ): Promise<Operator | null> {
    const result = await this.service.operator(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Operator)
  async createOperator(
    @graphql.Args() args: CreateOperatorArgs
  ): Promise<Operator> {
    return await this.service.createOperator({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Operator)
  async updateOperator(
    @graphql.Args() args: UpdateOperatorArgs
  ): Promise<Operator | null> {
    try {
      return await this.service.updateOperator({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Operator)
  async deleteOperator(
    @graphql.Args() args: DeleteOperatorArgs
  ): Promise<Operator | null> {
    try {
      return await this.service.deleteOperator(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
